# Generated by Django 5.2.9 on 2026-03-04 04:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employeephoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="hired_at",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Дата приёма на работу",
            ),
        ),
    ]
