# Generated by Django 5.2.9 on 2026-03-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "desk_number",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Номер стола"
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Кабинет / комната"
                    ),
                ),
                (
                    "has_monitor",
                    models.BooleanField(default=True, verbose_name="Монитор"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="Дополнительная информация"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рабочее место",
                "verbose_name_plural": "Рабочие места",
                "ordering": ["desk_number"],
            },
        ),
    ]
